# Generated by Django 6.0.3 on 2026-04-05 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10-digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('roll', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be exactly 7 digits', regex='^\\d{7}$')])),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
