# Generated by Django 6.0.3 on 2026-04-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('caste', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('tenth', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('plus2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('income', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('mother_aadhar', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('father_aadhar', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('dmc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsec.student')),
            ],
        ),
    ]
