# Generated by Django 6.0.3 on 2026-04-10 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsec', '0002_adminuser_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='caste',
            field=models.FileField(blank=True, null=True, upload_to='documents/caste/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dmc',
            field=models.FileField(blank=True, null=True, upload_to='documents/dmc/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='father_aadhar',
            field=models.FileField(blank=True, null=True, upload_to='documents/father/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='income',
            field=models.FileField(blank=True, null=True, upload_to='documents/income/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mother_aadhar',
            field=models.FileField(blank=True, null=True, upload_to='documents/mother/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='plus2',
            field=models.FileField(blank=True, null=True, upload_to='documents/plus2/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docsec.student'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenth',
            field=models.FileField(blank=True, null=True, upload_to='documents/tenth/'),
        ),
    ]
