# Generated by Django 6.0.3 on 2026-04-12 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsec', '0004_remove_document_updated_at_alter_document_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='name',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(default='9999999999', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10-digit phone number', regex='^[6-9]\\d{9}$')]),
            preserve_default=False,
        ),
    ]
