# Generated by Django 6.0.3 on 2026-04-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsec', '0005_adminuser_name_adminuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='1st', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='1st Year', max_length=20),
            preserve_default=False,
        ),
    ]
