# Generated by Django 6.0.3 on 2026-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsec', '0006_student_semester_student_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='f_name',
        ),
    ]
